name: build-all

on:
  workflow_call:

jobs:
  build-web:
    uses: ./.github/workflows/build-web.yml

  build-musl:
    needs:
      - build-web
    uses: ./.github/workflows/build-musl.yml

  build-gnu:
    needs:
      - build-web
    uses: ./.github/workflows/build-gnu.yml

  build-all:
    runs-on: ubuntu-latest
    needs:
      - build-web
      - build-musl
      - build-gnu
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fix cargo config
        run: sed -e "s/.*replace-with.*//g" -i .cargo/config

#      - name: Download web
#        uses: actions/download-artifact@v3
#        with:
#          name: pisugar-web
#          path: |
#            electron/dist
#
#      - name: Download amd64
#        uses: actions/download-artifact@v3
#        with:
#          name: pisugar-amd64
#          path: |
#            target
#
#      - name: Download arm
#        uses: actions/download-artifact@v3
#        with:
#          name: pisugar-arm
#          path: |
#            target
#
#      - name: Download armhf
#        uses: actions/download-artifact@v3
#        with:
#          name: pisugar-armhf
#          path: |
#            target
#
#      - name: Download aarch64
#        uses: actions/download-artifact@v3
#        with:
#          name: pisugar-aarch64
#          path: |
#            target

      - name: Download all
        uses: actions/download-artifact@v3
        with:
          path: |
            download

      - name: Move files
        run: |
          set -x
          mkdir -p electron/dist
          mv -f download/pisugar-web/* electron/dist/
          mkdir -p target
          for i in $(ls download); do
            mv -f download/$i/* target/
          fi

      - run: ls -r target

      # aur for archlinux
      - run: (cd scripts/aur; sh build-aur.sh)

      # Upload artifact
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pisugar-all
          path: |
            target/**/*.deb
            target/**/*.rpm
            !target/**/*src*.rpm
            scripts/*.sh
            scripts/aur/*.tar.gz
            !scripts/update-version.sh
          if-no-files-found: warn