name: PiSugar3

on:
  push:
    branches: [pisugar-3]

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fix cargo config
        run: sed -e "s/.*replace-with.*//g" -i .cargo/config

      # Nodejs npm cache
      - name: Nodejs npm cache
        uses: actions/cache@v1
        env:
          cache-name: cache-node-npm
        with:
          path: |
            ~/.npm
            electron/node_modules
            electron/dist
          key: ${{ runner.os }}-build-${{ env.cache-name }}
      # Nodejs
      - name: Setup Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      # Nodejs dependencies
      - run: npm install
        working-directory: electron
      # Nodejs build web
      - run: npm run build:web
        working-directory: electron

      # Rust cache
      - name: Rust cargo cache
        uses: actions/cache@v1
        env:
          cache-name: cache-rust-cargo
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-build-${{ env.cache-name }}
      # Rust musl cross cache arm
      - name: Rust musl cache
        uses: actions/cache@v1
        env:
          cache-name: cache-rust-musl
        with:
          path: |
            /opt/arm-linux-musleabihf-cross
            /opt/aarch64-linux-musl-cross
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      # Rust musl cross toolchain
      - name: Rust musl cross toolchain
        run: |
          if ! test -d /opt/arm-linux-musleabihf-cross/bin; then
            wget https://more.musl.cc/$(uname -m)-linux-musl/arm-linux-musleabihf-cross.tgz
            tar -xvf arm-linux-musleabihf-cross.tgz
            mv arm-linux-musleabihf-cross /opt/
          fi
          echo /opt/arm-linux-musleabihf-cross/bin >> $GITHUB_PATH
      # Rust musl cross toolchain aarch64
      - name: Rust musl cross toolchain aarch64
        run: |
          if ! test -d /opt/aarch64-linux-musl-cross/bin; then
            wget https://more.musl.cc/$(uname -m)-linux-musl/aarch64-linux-musl-cross.tgz
            tar -xvf aarch64-linux-musl-cross.tgz
            mv aarch64-linux-musl-cross /opt/
          fi
          echo /opt/aarch64-linux-musl-cross/bin >> $GITHUB_PATH
      # Fix libgcc.a for aarch64
      - run: |
          LIBGCC=$(find /opt/aarch64-linux-musl-cross -name libgcc.a)
          echo $LIBGCC
          sed -e "s|\"/opt/aarch64-linux-musl-cross/lib/gcc/aarch64-linux-musl/9.2.1\"|\"${LIBGCC%/*}\"|" -i .cargo/config
          cat .cargo/config

      # Rust toolchain
      - name: Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: rustup target add arm-unknown-linux-musleabihf
      - run: rustup target add aarch64-unknown-linux-musl
      - run: cargo install cargo-deb
      - run: cargo install cargo-rpm

      # Rust cargo deb - pisugar-server
      - run: cargo deb --target arm-unknown-linux-musleabihf --manifest-path=pisugar-server/Cargo.toml
      - run: cargo deb --target aarch64-unknown-linux-musl --manifest-path=pisugar-server/Cargo.toml
      - run: cargo deb --target arm-unknown-linux-musleabihf --manifest-path=pisugar-poweroff/Cargo.toml
      - run: cargo deb --target aarch64-unknown-linux-musl --manifest-path=pisugar-poweroff/Cargo.toml

      # Rust cargo-rpm
      - run: sudo apt update && sudo apt install -y rpm
      - run: (cd pisugar-server && cargo rpm build --target arm-unknown-linux-musleabihf)
      - run: (cd pisugar-server && cargo rpm build --target aarch64-unknown-linux-musl)
      - run: (cd pisugar-poweroff && cargo rpm build --target arm-unknown-linux-musleabihf)
      - run: (cd pisugar-poweroff && cargo rpm build --target aarch64-unknown-linux-musl)

      - run: find $(pwd) -name '*.deb'
      - run: find $(pwd) -name '*.rpm'

      # Upload artifact
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: pisugar-artifacts
          path: |
            target/arm-unknown-linux-musleabihf/debian/*
            target/aarch64-unknown-linux-musl/debian/*
            target/arm-unknown-linux-musleabihf/release/rpmbuild/RPMS/armv7hl/*
            target/aarch64-unknown-linux-musl/release/rpmbuild/RPMS/aarch64/*
            scripts/*
          if-no-files-found: warn

      # Development Release
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Development Build"
          prerelease: true
          draft: false
          files: |
            target/aarch64-unknown-linux-musl/debian/*
            target/arm-unknown-linux-musleabihf/debian/*
            target/aarch64-unknown-linux-musl/release/rpmbuild/RPMS/aarch64/*
            target/arm-unknown-linux-musleabihf/release/rpmbuild/RPMS/armv7hl/*
            scripts/*
