name: "Pre Release"

on:
  push:
    tags:
      - "v*"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Fix cargo config
        run: sed -e "s/.*replace-with.*//g" -i .cargo/config

      # Nodejs
      - name: Setup Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      # Nodejs dependencies
      - run: npm install
        working-directory: electron
      # Nodejs build web
      - run: npm run build:web
        working-directory: electron

      # Rust musl cross toolchain
      - name: Rust musl cross toolchain arm
        run: |
          if ! test -d /opt/arm-linux-musleabi-cross/bin; then
            wget https://more.musl.cc/$(uname -m)-linux-musl/arm-linux-musleabi-cross.tgz
            tar -xvf arm-linux-musleabi-cross.tgz
            mv arm-linux-musleabi-cross /opt/
          fi
          echo /opt/arm-linux-musleabi-cross/bin >> $GITHUB_PATH
      - name: Rust musl cross toolchain armhf
        run: |
          if ! test -d /opt/arm-linux-musleabihf-cross/bin; then
            wget https://more.musl.cc/$(uname -m)-linux-musl/arm-linux-musleabihf-cross.tgz
            tar -xvf arm-linux-musleabihf-cross.tgz
            mv arm-linux-musleabihf-cross /opt/
          fi
          echo /opt/arm-linux-musleabihf-cross/bin >> $GITHUB_PATH
      - name: Rust musl cross toolchain aarch64
        run: |
          if ! test -d /opt/aarch64-linux-musl-cross/bin; then
            wget https://more.musl.cc/$(uname -m)-linux-musl/aarch64-linux-musl-cross.tgz
            tar -xvf aarch64-linux-musl-cross.tgz
            mv aarch64-linux-musl-cross /opt/
          fi
          echo /opt/aarch64-linux-musl-cross/bin >> $GITHUB_PATH
      # Fix libgcc.a for aarch64
      - run: |
          LIBGCC=$(find /opt/aarch64-linux-musl-cross -name libgcc.a)
          echo $LIBGCC
          sed -e "s|\"/opt/aarch64-linux-musl-cross/lib/gcc/aarch64-linux-musl/9.2.1\"|\"${LIBGCC%/*}\"|" -i .cargo/config
          cat .cargo/config

      # Rust toolchain
      - name: Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: rustup target add arm-unknown-linux-musleabi
      - run: rustup target add arm-unknown-linux-musleabihf
      - run: rustup target add aarch64-unknown-linux-musl
      - run: cargo install cargo-deb
      - run: cargo install cargo-rpm

      # Rust cargo deb - pisugar-server
      - run: cargo deb --target arm-unknown-linux-musleabi --manifest-path=pisugar-server/Cargo.toml
      - run: cargo deb --target arm-unknown-linux-musleabihf --manifest-path=pisugar-server/Cargo.toml
      - run: cargo deb --target aarch64-unknown-linux-musl --manifest-path=pisugar-server/Cargo.toml
      - run: cargo deb --target arm-unknown-linux-musleabi --manifest-path=pisugar-poweroff/Cargo.toml
      - run: cargo deb --target arm-unknown-linux-musleabihf --manifest-path=pisugar-poweroff/Cargo.toml
      - run: cargo deb --target aarch64-unknown-linux-musl --manifest-path=pisugar-poweroff/Cargo.toml
      - run: cargo deb --target arm-unknown-linux-musleabi --manifest-path=pisugar-programmer/Cargo.toml
      - run: cargo deb --target arm-unknown-linux-musleabihf --manifest-path=pisugar-programmer/Cargo.toml
      - run: cargo deb --target aarch64-unknown-linux-musl --manifest-path=pisugar-programmer/Cargo.toml

      # Rust cargo-rpm
      - run: sudo apt update && sudo apt install -y rpm
      - run: (cd pisugar-server && cargo rpm build --target arm-unknown-linux-musleabi)
      - run: (cd pisugar-server && cargo rpm build --target arm-unknown-linux-musleabihf)
      - run: (cd pisugar-server && cargo rpm build --target aarch64-unknown-linux-musl)
      - run: (cd pisugar-poweroff && cargo rpm build --target arm-unknown-linux-musleabi)
      - run: (cd pisugar-poweroff && cargo rpm build --target arm-unknown-linux-musleabihf)
      - run: (cd pisugar-poweroff && cargo rpm build --target aarch64-unknown-linux-musl)
      - run: (cd pisugar-programmer && cargo rpm build --target arm-unknown-linux-musleabi)
      - run: (cd pisugar-programmer && cargo rpm build --target arm-unknown-linux-musleabihf)
      - run: (cd pisugar-programmer && cargo rpm build --target aarch64-unknown-linux-musl)

      - run: find $(pwd) -name '*.deb'
      - run: find $(pwd) -name '*.rpm'

      # Upload artifact
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: pisugar-artifacts
          path: |
            target/arm-unknown-linux-musleabi/debian/*
            target/arm-unknown-linux-musleabihf/debian/*
            target/aarch64-unknown-linux-musl/debian/*
            target/arm-unknown-linux-musleabihf/release/rpmbuild/RPMS/armv7l/*
            target/arm-unknown-linux-musleabihf/release/rpmbuild/RPMS/armv7hl/*
            target/aarch64-unknown-linux-musl/release/rpmbuild/RPMS/aarch64/*
            scripts/*
          if-no-files-found: warn

      # Draft Release
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          draft: true
          files: |
            target/arm-unknown-linux-musleabi/debian/*
            target/arm-unknown-linux-musleabihf/debian/*
            target/aarch64-unknown-linux-musl/debian/*
            target/arm-unknown-linux-musleabihf/release/rpmbuild/RPMS/armv7l/*
            target/arm-unknown-linux-musleabihf/release/rpmbuild/RPMS/armv7hl/*
            target/aarch64-unknown-linux-musl/release/rpmbuild/RPMS/aarch64/*
            scripts/*

      # Upload QiNiu nightly
      - name: "Upload to QiNiu"
        env:
          QINIU_BUCKET: ${{ secrets.QINIU_BUCKET }}
          QINIU_AK: ${{ secrets.QINIU_AK }}
          QINIU_SK: ${{ secrets.QINIU_SK }}
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip

          if [ $(uname -m) == 'x86_64' ]; then
            wget http://devtools.qiniu.com/qshell-linux-x64-v2.4.1.zip
            unzip qshell-linux-x64-v2.4.1.zip
            mv qshell-linux-x64-v2.4.1 qshell
          else
            wget http://devtools.qiniu.com/qshell-linux-x86-v2.4.1.zip
            unzip qshell-linux-x86-v2.4.1.zip
            mv qshell-linux-x86-v2.4.1 qshell
          fi
          chmod +x qshell
          ./qshell account -w ${QINIU_AK} ${QINIU_SK} deploy-account
          for f in $(find target -type f -name '*.deb') $(find target -type f -name '*.rpm'); do
            filename=${f##*/}
            key=nightly/${filename}
            ./qshell rput --overwrite ${QINIU_BUCKET} ${key} ${f}
          done
          for f in $(find scripts -name '*.sh' ); do
            filename=${f##*/}
            key=nightly/${filename}
            ./qshell rput --overwrite --mimetype text/plain ${QINIU_BUCKET} ${key} ${f}
          done
